variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprobligationcalc'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprobligationcalcrepository'
  serviceName: 'PRDRWDWEBFA1410'